
name: Windows Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build-x64-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Dependencies configuration
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          .\vcpkg.exe install glfw3 opengl sfml --triplet x64-windows

      - name: CMake configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: CMake build
        run: |
          cd build
          cmake --build . --config Release
